### ISSUE TITLE
No response from magnetometer

### ISSUE THREAD

**Issue by MaSkr09** [kriswiner/MPU9250#123]
Hi Kris
I’m working on a open source tracking device “DroneID”, for trafic management of drones in Denmark [DroneID_report](http://droneid.dk/download/DroneID_Report_October_2016.pdf). I have som trouble with a MPU-9250 sensor. I’ve tried to implement your solution, but went back to basics just to get started. The problem is that I don’t get any response from the magnetometer. There is no problem getting data from the other sensors in the chip, but when i get to the last line of the code below, I get an error.

Inspired by [lucidarme](http://www.lucidarme.me/?p=5057) 

  bool error = false;
  // Set accelerometers low pass filter at 5Hz
  data_test = 0x06;
  error |= i2c_write(0x68,29,1,&data_test);
  // Set gyroscope low pass filter at 5Hz
  error |= i2c_write(0x68,26,1,&data_test);
  // Configure gyroscope range
  data_test = 0x10;
  error |= i2c_write(0x68,27,1,&data_test);
  // Configure accelerometers range
  data_test = 0x08;
  error |= i2c_write(0x68,28,1,&data_test);
  // Set by pass mode for the magnetometers
  data_test = 0x02;
  error |= i2c_write(0x68,0x37,1,&data_test);
  
  // Request continuous magnetometer measurements in 16 bits
  data_test = 0x01
  error |= i2c_write(0x0C,0x0A,1,&data_test);

Do you have any idea of what could be wrong? 

Kind regards
Martin Skriver

**Comment by kriswiner** [comment]
0x01 is not a valid entry, please see the data sheet.

```
void initAK8963(float * destination)
{
  // First extract the factory calibration for each magnetometer axis
  uint8_t rawData[3];  // x/y/z gyro calibration data stored here
  writeByte(AK8963_ADDRESS, AK8963_CNTL, 0x00); // Power down magnetometer  
  delay(10);
  writeByte(AK8963_ADDRESS, AK8963_CNTL, 0x0F); // Enter Fuse ROM access mode
  delay(10);
  readBytes(AK8963_ADDRESS, AK8963_ASAX, 3, &rawData[0]);  // Read the x-, y-, and z-axis calibration values
  destination[0] =  (float)(rawData[0] - 128)/256. + 1.;   // Return x-axis sensitivity adjustment values, etc.
  destination[1] =  (float)(rawData[1] - 128)/256. + 1.;  
  destination[2] =  (float)(rawData[2] - 128)/256. + 1.; 
  writeByte(AK8963_ADDRESS, AK8963_CNTL, 0x00); // Power down magnetometer  
  delay(10);
  // Configure the magnetometer for continuous read and highest resolution
  // set Mscale bit 4 to 1 (0) to enable 16 (14) bit resolution in CNTL register,
  // and enable continuous mode data acquisition Mmode (bits [3:0]), 0010 for 8 Hz and 0110 for 100 Hz sample rates
  writeByte(AK8963_ADDRESS, AK8963_CNTL, Mscale << 4 | Mmode); // Set magnetometer data resolution and sample ODR
  delay(10);
}
```

**Comment by MaSkr09** [comment]
Thank you for your fast respond. 0x01 was my panic attempt to try something new :) I tried implementing the code, but it didn’t change anything. It seems like there is no node with addr 0x0C on the bus. 
Do you think it can it be a hardware problem? It is just strange since there is no problem getting data from node addr 0x68.

Kind regards

**Comment by kriswiner** [comment]
If you set bypass by writing 0x02 to the INT_CFG register this should allow
discovery of the AK8963C by an I2C scanner.

Why don't you try a known good Arduino sketch?

https://github.com/kriswiner/MPU-9250/blob/master/MPU9250_MS5637_AHRS_t3.ino

**Comment by MaSkr09** [comment]
Thanks Kris 
I'll try working with it tomorrow and get back with the result.

**Comment by MaSkr09** [comment]
Still no response fra AK8963C. 
I attached the MPU9250 part of the diagram that we used in the DroneID. I have seen diagrams of the sensor where pin 1 is open. We added 3 V to the pin. Is that correct?

![image](https://cloud.githubusercontent.com/assets/3857288/23796288/78d003c6-059a-11e7-8bd4-a20e217b0983.png)

Kind regards

**Comment by kriswiner** [comment]
The schematic looks OK except I would not connect the pad to anything and
would have no copper on any layer beneath the package. I doubt this is
causing the problem with the mag unless the pad is bridging one of the pins.

**Comment by MaSkr09** [comment]
I had a problem with the I2C but it is working now.
Thank you very much, I owe you a beer ;)

**Comment by vahidyazdnian13** [comment]
> 
> 
> I had a problem with the I2C but it is working now. Thank you very much, I owe you a beer ;)

hello ! i have a very similar problem to what you had an my I2C doesn't connect to 0x0C address to get data can you help me out and tell me what did you do to solve this please!

**Comment by ethem4161** [comment]
> > I2C ile ilgili bir sorunum vardı ama şimdi çalışıyor. Çok teşekkür ederim, sana bir bira borcum var ;)
> 
> Merhaba ! sahip olduğunuza çok benzer bir sorunum var, I2C'm veri almak için 0x0C adresine bağlanmıyor, bana yardım edebilir ve bunu çözmek için ne yaptığınızı söyleyebilir misiniz lütfen!

+1

**Comment by kriswiner** [comment]
English please...

**Comment by locissigtech** [comment]
I'm using a Raspberry Pi with a MPU9250, and I'm having similar problem. Everything works fine (if I add in python a try/except block) except for the magnetometer. Im running the command i2cdetect -y 1 to scan the addresses. The 0x68 of the accel/gyro is appearing, but the 0x0c is not showing up. Could someone help me? I know this is not talking about python, but...

**Comment by kriswiner** [comment]
You have to enable I2C pass through to allow the magnetometer to be
addressed by the host MCU.

**Comment by tharunrp06** [comment]
> I had a problem with the I2C but it is working now. Thank you very much, I owe you a beer ;)

I am too experiencing similar issue where the Magnetometer is not responding for the I2C...the address 0x0C is not detected...how did you resolve it? I have entered the bypass mode and disabled the master I2C also still facing the same issue

**Comment by kriswiner** [comment]
Not sure what to say here. I assume you are taking the usual steps to read
the mag like verifying I2C works on the accel/gyro, placing the MPU6500
into bypass mode, etc. There is no magic spell to make this work, just
follow the data sheets and sample Arduino code.

There have always been a lot of "fake" MPU9250s out there, more so since
the MPU9250 went out of production 7 or 8 years ago. It is likely you have
one of the Invensense variants that do not have a magnetometer, just the
MPU6500 combo accel/gyro. Lots of unscrupulous (or ignorant) Chinese
retailers sell these as MPU9250 since there is still high demand for this
sensor.

My recommendation is to buy an MPU9250 breakout board from a reputable
seller like Sparkfun, Adafruit, etc (if you can still find one) to test and
develop your code. I have had to throw away a fair number of "MPU9250
sensors" I bought on Aliexpress that turned out to be something else....
